language: node_js

node_js:
- '6'

script:
- npm run build

after_success:
- git branch -a
- git remote set-branches --add origin gh-pages
- git fetch
- git branch -a
- git checkout -f origin/gh-pages
- shopt -s extglob
- rm -rf ./!(gh-pages)
- mv -f ./gh-pages/* ./
- rm -rf ./gh-pages
- git config user.name "$GIT_USER_NAME"
- git config user.email "$GIT_USER_EMAIL"
- git add --all
- git commit -m "Deploy to GitHub Pages by Travis $TRAVIS_COMMIT"
- git push -f "$GITHUB_REPO_GIT" master:gh-pages --quiet
- ls -l

cache:
  bundler: true

os:
- linux

branches:
  only:
  - master

env:
  global:
    secure: PG52vqgFb/rW3c9J72wrrKD6pTuV0FPur0YVrJwGSrvGANouGXMBHVX521q7wlnZGklqqFNc2Hh2uxW96ajFq/lqjuV1bKD9Y4dIziiCsXACQqExaeVjRWOP4FIKBGgevqCQ3nFo/9hj0fR0/Mly0lBFc0UKCtO57ASGtV0b1l9Q18udJ7Fm5WiqGq0MiS+GjxRrcMZNRqSEB8bG6dcRzavqW8DpIILv7zKC6v9PWppodRRputXHvMz+vu86IklPNuFYg8+ppfeAYiRc0pyoy2ysnze+adIC928pSuGzSrJR6DN8JJxiOK5qaT8ZNaI6ednsolhWuFHxAvUpLti4OcHd6iMKsZH4PVcraFzW36pxm/CenlvvMZD5KYloqpqtmqlFJt5pGd4JNkxiAHXBt7FEldMKSvP5k5ecoaU97rNK+OCOgXvxnZb102LB4eKkUfflTyRe8/eAPMIy0YLjjggUwXuoaXylCbpI2twY9WKTX3z7NJCNNlV1NYOm3xIKhrFLQvwDKy240VkTsEwtE3fm269TUoHeSVucE6KtEHDNN9AOLYmf7jnxnEAHohw080tK6eBIFCTrwLXhmQ/98bpEZBvK6CcbE2/US1s9ntGY8uxobDXo9W916LJ9Hgebda54RPj26kJ8YawnYWL+erszj8w5av9CKx/kCB+xb6o=
